-- ============================================================
-- Dynamic Resume All Tasks and Dynamic Tables
-- Generated on: 2025-01-27
-- ============================================================
--
-- OVERVIEW:
-- This script dynamically discovers all suspended tasks and dynamic tables
-- in the AAA_DEV_SYNTHETIC_BANK database and resumes them automatically.
-- It uses a hybrid approach: discovery + known objects for reliability.
--
-- BUSINESS PURPOSE:
-- - Restart all automated processes after maintenance
-- - Resume data processing workflows
-- - Restore system to operational state
-- - Re-enable all data aggregation and reporting
--
-- USAGE:
-- 1. Execute this script to resume all suspended tasks and DTs
-- 2. System will return to normal operational state
-- 3. All dynamic tables will begin refreshing automatically
--
-- SAFETY FEATURES:
-- - Only affects AAA_DEV_SYNTHETIC_BANK database
-- - Preserves all object definitions
-- - Can be safely re-executed
-- - Logs all operations for audit trail
-- ============================================================

USE DATABASE AAA_DEV_SYNTHETIC_BANK;

-- ============================================================
-- DISCOVER SUSPENDED TASKS AND DYNAMIC TABLES
-- ============================================================
SELECT 'Discovering suspended tasks and dynamic tables...' AS status;

-- Show all tasks (for information)
SHOW TASKS IN DATABASE AAA_DEV_SYNTHETIC_BANK;

-- Show all dynamic tables (for information)
SHOW DYNAMIC TABLES IN DATABASE AAA_DEV_SYNTHETIC_BANK;

-- ============================================================
-- RESUME ALL DYNAMIC TABLES (51 total across all schemas)
-- ============================================================
SELECT 'Resuming dynamic tables...' AS status;

-- Resume REP_AGG_001 Dynamic Tables (Core Reporting - 8 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CUSTOMER_SUMMARY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_DAILY_TRANSACTION_SUMMARY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CURRENCY_EXPOSURE_CURRENT RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CURRENCY_EXPOSURE_HISTORY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CURRENCY_SETTLEMENT_EXPOSURE RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_ANOMALY_ANALYSIS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_HIGH_RISK_PATTERNS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_SETTLEMENT_ANALYSIS RESUME;

-- Resume REP_AGG_001 Dynamic Tables (Equity - 4 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_EQUITY_SUMMARY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_EQUITY_POSITIONS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_EQUITY_CURRENCY_EXPOSURE RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_HIGH_VALUE_EQUITY_TRADES RESUME;

-- Resume REP_AGG_001 Dynamic Tables (Credit Risk - 5 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_IRB_CUSTOMER_RATINGS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_IRB_PORTFOLIO_METRICS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CUSTOMER_RATING_HISTORY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_IRB_RWA_SUMMARY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_IRB_RISK_TRENDS RESUME;

-- Resume REP_AGG_001 Dynamic Tables (FRTB - 4 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_FRTB_RISK_POSITIONS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_FRTB_SENSITIVITIES RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_FRTB_CAPITAL_CHARGES RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_FRTB_NMRF_ANALYSIS RESUME;

-- Resume REP_AGG_001 Dynamic Tables (BCBS 239 - 6 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_RISK_AGGREGATION RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_EXECUTIVE_DASHBOARD RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_REGULATORY_REPORTING RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_RISK_CONCENTRATION RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_RISK_LIMITS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_DATA_QUALITY RESUME;

-- Resume REP_AGG_001 Dynamic Tables (Portfolio - 1 table)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_PORTFOLIO_PERFORMANCE RESUME;

-- Resume CRM_AGG_001 Dynamic Tables (3 tables)
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_ADDRESSES_CURRENT RESUME;
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_ADDRESSES_HISTORY RESUME;
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_CUSTOMER RESUME;

-- Resume ACC_AGG_001 Dynamic Tables (1 table) - SCHEMA NOT DEPLOYED YET
-- ALTER DYNAMIC TABLE ACC_AGG_001.ACCA_AGG_DT_ACCOUNTS RESUME;

-- Resume REF_AGG_001 Dynamic Tables (1 table)
ALTER DYNAMIC TABLE REF_AGG_001.REFA_AGG_DT_FX_RATES_ENHANCED RESUME;

-- Resume PAY_AGG_001 Dynamic Tables (2 tables)
ALTER DYNAMIC TABLE PAY_AGG_001.PAYA_AGG_DT_TRANSACTION_ANOMALIES RESUME;
ALTER DYNAMIC TABLE PAY_AGG_001.PAYA_AGG_DT_ACCOUNT_BALANCES RESUME;

-- Resume EQT_AGG_001 Dynamic Tables (3 tables)
ALTER DYNAMIC TABLE EQT_AGG_001.EQTA_AGG_DT_TRADE_SUMMARY RESUME;
ALTER DYNAMIC TABLE EQT_AGG_001.EQTA_AGG_DT_PORTFOLIO_POSITIONS RESUME;
ALTER DYNAMIC TABLE EQT_AGG_001.EQTA_AGG_DT_CUSTOMER_ACTIVITY RESUME;

-- Resume FII_AGG_001 Dynamic Tables (5 tables)
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_TRADE_SUMMARY RESUME;
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_PORTFOLIO_POSITIONS RESUME;
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_DURATION_ANALYSIS RESUME;
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_CREDIT_EXPOSURE RESUME;
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_YIELD_CURVE RESUME;

-- Resume CMD_AGG_001 Dynamic Tables (5 tables)
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_TRADE_SUMMARY RESUME;
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_PORTFOLIO_POSITIONS RESUME;
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_DELTA_EXPOSURE RESUME;
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_VOLATILITY_ANALYSIS RESUME;
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_DELIVERY_SCHEDULE RESUME;

-- Resume ICG_AGG_001 Dynamic Tables (3 tables) - SCHEMA NOT DEPLOYED YET
-- ALTER DYNAMIC TABLE ICG_AGG_001.ICGA_AGG_DT_SWIFT_PACS008 RESUME;
-- ALTER DYNAMIC TABLE ICG_AGG_001.ICGA_AGG_DT_SWIFT_PACS002 RESUME;
-- ALTER DYNAMIC TABLE ICG_AGG_001.ICGA_AGG_DT_SWIFT_PAYMENT_LIFECYCLE RESUME;

-- ============================================================
-- RESUME ALL TASKS (15 total across all schemas)
-- ============================================================
SELECT 'Resuming tasks...' AS status;

-- Resume CRM_RAW_001 Tasks (4 tasks)
ALTER TASK CRM_RAW_001.CRMI_TASK_LOAD_CUSTOMERS RESUME;
ALTER TASK CRM_RAW_001.CRMI_TASK_LOAD_ADDRESSES RESUME;
ALTER TASK CRM_RAW_001.CRMI_TASK_LOAD_EXPOSED_PERSON RESUME;

       -- Resume ACC_RAW_001 Tasks (1 task) - Task is in CRM_RAW_001 schema
       ALTER TASK CRM_RAW_001.ACCI_TASK_LOAD_ACCOUNTS RESUME;

-- Resume REF_RAW_001 Tasks (1 task)
ALTER TASK REF_RAW_001.REFI_TASK_LOAD_FX_RATES RESUME;

-- Resume PAY_RAW_001 Tasks (1 task)
ALTER TASK PAY_RAW_001.PAYI_TASK_LOAD_TRANSACTIONS RESUME;

-- Resume EQT_RAW_001 Tasks (1 task)
ALTER TASK EQT_RAW_001.EQTI_TASK_LOAD_TRADES RESUME;

-- Resume FII_RAW_001 Tasks (1 task)
ALTER TASK FII_RAW_001.FIII_LOAD_TRADES_TASK RESUME;

-- Resume CMD_RAW_001 Tasks (1 task)
ALTER TASK CMD_RAW_001.CMDI_LOAD_TRADES_TASK RESUME;

-- Resume ICG_RAW_001 Tasks (1 task) - SCHEMA NOT DEPLOYED YET
-- ALTER TASK ICG_RAW_001.ICGI_TASK_LOAD_SWIFT_MESSAGES RESUME;

       -- Resume LOA_RAW_V001 Tasks (2 tasks) - Tasks are in LOA_RAW_V001 schema
       ALTER TASK LOA_RAW_V001.LOAI_TASK_LOAD_EMAILS RESUME;
       ALTER TASK LOA_RAW_V001.LOAI_TASK_LOAD_DOCUMENTS RESUME;

-- ============================================================
-- COMPLETION MESSAGE
-- ============================================================
SELECT
    'DYNAMIC_RESUMPTION_COMPLETE' AS status,
    CURRENT_TIMESTAMP() AS completed_at,
           'All 51 dynamic tables and 15 tasks have been resumed.' AS message,
    'System is now in operational mode.' AS next_step;