-- ============================================================
-- Snowflake Data Exchange - Global Sanctions Data Setup
-- Generated on: 2025-01-XX
-- ============================================================
--
-- OVERVIEW:
-- This script sets up access to the Global Sanctions Data Set from Snowflake's
-- Data Exchange marketplace. This provides real-time sanctions and watchlist
-- data for compliance screening and regulatory reporting.
--
-- BUSINESS PURPOSE:
-- - Import global sanctions data for PEP (Politically Exposed Persons) screening
-- - Enable compliance checking against international sanctions lists
-- - Support regulatory reporting and risk management
-- - Provide reference data for customer onboarding and transaction monitoring
--
-- DATA SOURCE:
-- - Snowflake Data Exchange Listing ID: GZT1ZVEJH9
-- - Global Sanctions Data Set with comprehensive international coverage
-- - Regular updates for current sanctions and watchlist information
--
-- PREREQUISITES:
-- - Snowflake account with Data Exchange access
-- - Legal terms acceptance for data usage
-- - Email verification for listing access
--
-- OBJECTS CREATED:
-- ┌─ DATABASES (1):
-- │  └─ REF_DAP_GLOBAL_SANCTIONS_DATA_SET - Global sanctions data database
-- │
-- ├─ SCHEMAS (1):
-- │  └─ GLOBAL_SANCTIONS_DATA - Sanctions data schema
-- │
-- ├─ TABLES (1):
-- │  └─ SANCTIONS_DATAFEED - Global sanctions and watchlist data
-- │
-- └─ ACCESS (1):
--    └─ Data Exchange listing access for real-time updates
--
-- DATA ARCHITECTURE:
-- Data Exchange → Database Creation → Schema Access → Table Usage
--
-- REFRESH STRATEGY:
-- - Automatic updates from Data Exchange provider
-- - Real-time access to latest sanctions information
-- - No manual refresh required
--
-- RELATED SCHEMAS:
-- - CRM_RAW_001: Customer data for sanctions screening
-- - PAY_RAW_001: Transaction monitoring for compliance
-- - EQT_RAW_001: Investment screening for sanctions
-- ============================================================

-- ============================================================
-- DATA EXCHANGE SETUP - Global Sanctions Data Access
-- ============================================================
-- Step 1: Discover available listings (commented out - run manually if needed)
-- Get the global name and title of listings and filter on the title
-- SELECT "global_name", "title"
--   FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
--   WHERE "is_imported" = false
--     AND "title" LIKE '%Sanction%';

-- Step 2: Request access to the Global Sanctions Data listing
-- This initiates the listing request and waits for approval
CALL SYSTEM$REQUEST_LISTING_AND_WAIT('GZT1ZVEJH9');

-- Step 3: Accept legal terms for data usage
-- Email verification is required to create the database from listing
CALL SYSTEM$ACCEPT_LEGAL_TERMS('DATA_EXCHANGE_LISTING', 'GZT1ZVEJH9');

-- ============================================================
-- DATABASE CREATION - Global Sanctions Data Import
-- ============================================================
-- Step 4: Create database from the Data Exchange listing
-- This creates a new database with the sanctions data
-- Note: If database already exists, this will show an error but deployment continues
-- The error "Importing more than once is not supported" is expected and OK

DROP DATABASE if exists REF_DAP_GLOBAL_SANCTIONS_DATA_SET;

CREATE Database if not exists REF_DAP_GLOBAL_SANCTIONS_DATA_SET
  FROM LISTING 'GZT1ZVEJH9';

-- ============================================================
-- DATA EXPLORATION AND USAGE
-- ============================================================
-- USE SCHEMA GLOBAL_SANCTIONS_DATA;
-- Once the database is created, you can explore the sanctions data:
--
-- -- Query the 'SANCTIONS_DATAFEED' table and limit the results to 10 rows
-- SELECT * FROM SANCTIONS_DATAFEED LIMIT 10;
--
-- -- Count total sanctions records
-- SELECT COUNT(*) as TOTAL_SANCTIONS FROM SANCTIONS_DATAFEED;
--
-- -- Check data freshness
-- SELECT MAX(LAST_UPDATED) as LATEST_UPDATE FROM SANCTIONS_DATAFEED;
--
-- -- Sample sanctions by country
-- SELECT COUNTRY, COUNT(*) as SANCTIONS_COUNT 
-- FROM SANCTIONS_DATAFEED 
-- GROUP BY COUNTRY 
-- ORDER BY SANCTIONS_COUNT DESC 
-- LIMIT 10;
--
-- ============================================================
-- SETUP COMPLETION STATUS
-- ============================================================
-- ✅ Global Sanctions Data Setup Complete
--
-- OBJECTS CREATED:
-- • 1 Database: REF_DAP_GLOBAL_SANCTIONS_DATA_SET
-- • 1 Schema: GLOBAL_SANCTIONS_DATA
-- • 1 Table: SANCTIONS_DATAFEED
-- • 1 Access: Data Exchange listing access
--
-- NEXT STEPS:
-- 1. ✅ Global Sanctions Data setup completed successfully
-- 2. Verify database access: USE DATABASE REF_DAP_GLOBAL_SANCTIONS_DATA_SET;
-- 3. Check data availability: SELECT COUNT(*) FROM SANCTIONS_DATAFEED;
-- 4. Test sanctions screening in CRM_RAW_001 schema
-- 5. Integrate with compliance workflows
--
-- USAGE EXAMPLES:
-- -- Access the sanctions database
-- USE DATABASE REF_DAP_GLOBAL_SANCTIONS_DATA_SET;
-- USE SCHEMA GLOBAL_SANCTIONS_DATA;
-- 
-- -- Query sanctions data
-- SELECT * FROM SANCTIONS_DATAFEED LIMIT 10;
--
-- -- Check data freshness
-- SELECT MAX(LAST_UPDATED) as LATEST_UPDATE FROM SANCTIONS_DATAFEED;
--
-- -- Sample sanctions by country
-- SELECT COUNTRY, COUNT(*) as SANCTIONS_COUNT 
-- FROM SANCTIONS_DATAFEED 
-- GROUP BY COUNTRY 
-- ORDER BY SANCTIONS_COUNT DESC 
-- LIMIT 10;
-- ============================================================
-- Global Sanctions Data Setup Complete!
-- ============================================================